### ISSUE TITLE
[EmergencePsi] error: 'iscategorical' undefined near line 37, column 37

### ISSUE THREAD

**Issue by r03ert0** [pmediano/ReconcilingEmergences#1]
Hello,
I loved the paper! I'm trying to run the example from the `Readme.md`, but it's been ages that I don't use Octave (my last copy of Matlab was from 2012...). I'm in a Mac, and I installed a fresh copy of Octave using `brew install octave`. I copied the following code:

```octave
T = 1000;
X = zeros([T,2]);
for t=2:T
  X(t,1) = xor(X(t-1,1), X(t-1,2));
  X(t,2) = rand < 0.5;
end

V = xor(X(:,1), X(:,2));
psi   = EmergencePsi(X, V);
```

and I get the following error when executing `EmergencePsi`:

```
error: 'iscategorical' undefined near line 37, column 37

The 'iscategorical' function is not yet implemented in Octave.

Please read <https://www.octave.org/missing.html> to learn how you can
contribute missing functionality.
error: called from
    EmergencePsi at line 37 column 3
```

(side note: would it be within the means of a novice to write a Python version of your code?)

Thank you !

**Comment by pmediano** [comment]
Thanks for your kind words!

... and whoops! That seems like an easily avoidable Octave killer. I'll fix this to make it Octave-compatible and update you on this issue. In the meantime, you can compute things in continuous data by specifying the method explicitly:

```octave
psi = EmergencePsi(randn([100,2]), randn([100,1]), 1, 'gaussian');
```

Regarding the Python version: of course! Although (after the Octave-compatible fix has been pushed) you can just call this code from Python using the amazing [oct2py](https://blink1073.github.io/oct2py/) package. For example, from the root of this repo you can simply call:

```python
from oct2py import Oct2Py
import numpy.random as rn

oc = Oct2Py()
psi = oc.EmergencePsi(rn.randn(100,2), rn.randn(100,1), 1, 'gaussian');
```

**Comment by r03ert0** [comment]
Thank you Pedro! That works! 💃 
I'll give a try to `oct2py`. That will also help to check that I get the same results in the different languages 😛

**Comment by pmediano** [comment]
Hi again,

Commit a92381c should fix this issue and make all the code Octave-compatible. Please give it a try and let me know if it works so we can close this issue.

Thanks for bringing this up!
Pedro

**Comment by r03ert0** [comment]
that solved the issue 🚀 
now I get:

```octave
octave:8> psi   = EmergencePsi(X, V);
octave:9> psi
psi = 6.9756e-04
octave:10> delta = EmergenceDelta(X, V, 1);
octave:11> delta
delta = 0.9970
```
Thank you!
